### ISSUE TITLE
Limit tool to USAID and CDC

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/sims_site_selection#1]
Per Shabeen, the tool only needs to be for USAID and CDC. DOD and Peacecorp "do their own thing"

**Comment by achafetz** [comment]
:+1:

**Comment by achafetz** [comment]
Import data and then filter for only USAID and CDC

https://github.com/USAID-OHA-SI/sims_site_selection/blob/396ccc3a1d843c21b50b71a0c50f7910fa8cd10e/R/combine_output.r#L18-L19
